# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4a88ef740c3e48876b1acd7848d4bba0b3a2d0f19bfb0581e0ae671329254abe16357c4d5395d47be95a079a6a84a3cb181978773c0d0ac2645b04bc6c6638

test:
  secret_key_base: 21ce64861f03987002b283fba536479a4ae2ee5442f7d0890887613dc96706bb58d2a13f3834d069e30d9d45e3a52a504fe196caff7abd8eb4ca33d75f706a6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
